### PR TITLE
Allow Pattern creation from game object

### LINKED ISSUE #217: Allow Pattern-Creation from existing games
On the first glance this should not be too hard to implement, and we'd not need to change this point in reference to the Pflichtenheft

### PR DESCRIPTION
**Pull request by SeineEloquenz**
Todo:

- [x] Allow pattern creation from games
- [x] Add button to frontend
- [x] Add modal to get pattern title from organiser
- [x] Add necessary API endpoint (if not already exists)
- [x] Add necessary calls from API to backend

close #217

### CODE REVIEW

**Comment by bendixsonnenberg** [comment]
ill need a method on the organiser for creating a pattern from a game Id and title

**Comment by bendixsonnenberg** [comment]
@Weitspringer could you handle the modal for asking the user for the title of the new pattern? you have more practice than I do with modals

**Comment by Weitspringer** [comment]
@bendixsonnenberg looking into it

**Comment by SeineEloquenz** [comment]
@bendixsonnenberg the method is created and being called in the API

**Comment by Weitspringer** [comment]
Every time trying to call API this Error occurs:

java.lang.NumberFormatException: For input string: "{"isTrusted":true}"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.base/java.lang.Integer.parseInt(Integer.java:652)
        at java.base/java.lang.Integer.parseInt(Integer.java:770)
        at com.csselect.API.httpAPI.GameManagement.createPatternFromGame(GameManagement.java:93)
        at com.csselect.API.httpAPI.GameManagement.post(GameManagement.java:86)

**Comment by SeineEloquenz** [comment]
As we don't check duplicate patterns on game creation, we shouldn't do this here for consistency

**Comment by Weitspringer** [comment]
@SeineEloquenz  Of course we did?

**Comment by bendixsonnenberg** [comment]
we check for duplicate databases and duplicate game title, but not duplicate pattern

**Comment by Weitspringer** [comment]
We check in the frontend

**Pull request merged**
